let manifest = [
    {
        src:"spritesheet.js",
        id:"spritesheet"
    },
    {
        src:"lib/jump.ogg",
        id:"jumpSound",
        data:4
    },
    {
        src:"lib/hurt.ogg",
        id:"hurtSound",
        data:4
    },
    {
        src:"lib/slash.ogg",
        id:"slashSound",
        data:4
    },
    {
        src:"lib/die.ogg",
        id:"deathSound",
        data:4
    }  
];